version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mymusicapi_web_dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mymusicapi.settings.dev
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mymusicapi_db_dev
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mymusicapi_db_volume:/var/lib/postgresql/data

volumes:
  mymusicapi_db_volume:
