# Generated by Django 5.2.7 on 2025-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField(max_length=30)),
                ("genre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "ordering": ["year", "artist"],
            },
        ),
    ]
