# Generated by Django 5.2.7 on 2025-10-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="year",
            field=models.IntegerField(),
        ),
    ]
