name: Django Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: mymusicapi_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: mymusicapi.settings.base
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/mymusicapi_test
      PYTHONPATH: ./backend
      SECRET_KEY: testsecretkey

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements/test.txt

      - name: Run migrations
        run: |
          python backend/manage.py migrate --noinput

      - name: Run tests
        run: |
          pytest backend/albums --disable-warnings --maxfail=1 -q
